// Runnable migrator — applies the committed SQL migrations under apps/api/drizzle/.
//
// The migrations themselves are generated by `drizzle-kit generate` (see apps/api/drizzle.config.ts)
// and committed as plain SQL; this module only APPLIES them. It opens a dedicated single-connection
// pool (migrations must run serially), runs drizzle's migrator, and always closes the pool.
//
// Usage:
//   MOCK_MODE=0 DATABASE_URL=postgres://… tsx src/db/migrate.ts
// or programmatically: `await runMigrations(env.databaseUrl)` from a deploy step.
import { fileURLToPath, pathToFileURL } from 'node:url';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { loadEnv } from '../env';

/** Absolute path to the committed migrations folder (apps/api/drizzle), resolved from this file. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));

/**
 * Apply all pending migrations against `databaseUrl`. Uses a single serial connection and closes
 * it before resolving. Rejects if `databaseUrl` is empty (there is nothing to migrate in mock mode).
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  if (databaseUrl === '') {
    throw new Error(
      'runMigrations requires a non-empty DATABASE_URL (nothing to do in MOCK_MODE).',
    );
  }
  const sql = postgres(databaseUrl, { max: 1 });
  try {
    const db = drizzle(sql);
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await sql.end();
  }
}

// Run directly (`tsx src/db/migrate.ts`), never on import by tests.
const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  const env = loadEnv();
  runMigrations(env.databaseUrl)
    .then(() => {
      console.log('migrations applied');
    })
    .catch((err: unknown) => {
      console.error(err);
      process.exit(1);
    });
}
